services:
  purpleair2mqtt:
    image: cdzombak/purpleair2mqtt:1
    container_name: purpleair2mqtt
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config.toml:/config.toml:ro
